version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mysql_volume:/var/lib/mysql
    networks:
      - deep-sea
    tty: true

  spring:
    image: my_spring
    build:
      context: ./backend-spring
      args:
        - GIT_URL=${BACKEND_GIT_URL}
        - GIT_BRANCH=${BACKEND_GIT_BRANCH}
        - MY_WORKDIR=${BACKEND_WORKDIR}
    container_name: spring
    depends_on:
      - mysql
    restart: always
    env_file:
      - .env
    ports:
      - "${SPRING_PORT}:${SPRING_PORT}"
    volumes:
      - spring_volume:/Backend
    networks:
      - deep-sea
    tty: true

  react:
    image: my_react
    build:
      context: ./frontend-react
      args:
        - GIT_URL=${FRONTEND_GIT_URL}
        - GIT_BRANCH=${FRONTEND_GIT_BRANCH}
        - MY_WORKDIR=${FRONTEND_WORKDIR}
    container_name: react
    depends_on:
      - spring
    restart: always
    env_file:
      - .env
    ports:
      - "${REACT_PORT}:${REACT_PORT}"
    volumes:
      - react_volume:/Frontend
    networks:
      - deep-sea
    tty: true

volumes:
  mysql_volume:
  spring_volume:
  react_volume:

networks:
  deep-sea:
    driver: bridge
