version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mysql_volume:/var/lib/mysql
    networks:
      - 42_network
    tty: true

  spring:
    image: my_spring
    build:
      context: ./backend-spring
      args:
        - GIT_URL=${BACKEND_GIT_URL}
        - GIT_BRANCH=${BACKEND_GIT_BRANCH}
        - MY_WORKDIR=${BACKEND_WORKDIR}
    container_name: spring
    depends_on:
      - mysql
    restart: always
    env_file:
      - .env
    ports:
      - "${SPRING_PORT}:${SPRING_PORT}"
    volumes:
      - spring_volume:/Backend
    networks:
      - 42_network
    tty: true

volumes:
  mysql_volume:
  spring_volume:

networks:
  42_network:
    driver: bridge
